### ISSUE TITLE
Extension is broken due to new YouTube Premium Bitrate option

### ISSUE THREAD

**Issue by veredis** [sameernyaupane/simple-auto-hd#3]
YouTube recently released a new Premium Bitrate 1080p feature. This has broken this extension since now on every video, the extension tries to select the highest resolution option, which is the premium bitrate option, and this causes a popup from clicking that which asks you to sign up to YouTube Premium to use the feature.

**Comment by sameernyaupane** [comment]
Thanks for the heads up veredis.
I haven't seen this happen to me. Could you please take a screenshot and let me know how the video quality option appears?
It'll help me fix it out, thanks.

**Comment by veredis** [comment]
Here you go, sorry, I meant to post a picture to begin with: https://postimg.cc/5XhNzdnt

It's under the Settings Cog, then Quality. I've set the extension to use 1080p for now as a temporary fix.

Also, apparently this is just an experiment by YouTube and not everyone has it. Here's an article about it: https://www.gadgets360.com/apps/news/youtube-premium-1080p-enhanced-bitrate-video-quality-reddit-3807742

**Comment by veredis** [comment]
I was hoping the new update would address this issue, but it is still occurring.

I have not been able to use the "Best available quality" option since this YouTube change. If I enable it, this pops up on half the videos I watch: https://postimg.cc/8FDb9QLR

**Comment by sameernyaupane** [comment]
It is very hard for me to debug this without me able to see the html elements related to this. Since we target the element for the quality toggle to work. Are you by any chance good at Javascript? If so, please send me a PR.  Thanks

**Comment by veredis** [comment]
I understand. Unfortunately I only know the very basics of Javascript. I can follow somewhat technical instructions if you can tell me what to look for.

Otherwise, I assume YouTube will eventually roll out this feature to everyone, so we might just have to wait until then.

**Comment by sameernyaupane** [comment]
Please run this code on DevTools Console and give me the output.
To open DevTools console press keys: Ctrl + Shift+ I
Then click the "Console" tab on the menu.
Just paste the whole thing at the same time on the console tab within DevTools.

Note: You must be watching a youtube video  which has the premium option selection for this to work. 
Run the code in that same window's DevTools Console.

```
var settingsButton = document.getElementsByClassName('ytp-settings-button')[0];
settingsButton.click();
var buttons = document.getElementsByClassName('ytp-menuitem-label');
for (var i = 0; i < buttons.length; i++) {
    if(buttons[i].innerHTML == 'Quality') {
        buttons[i].click();
    }
};
var targetItems = document.querySelectorAll('.ytp-quality-menu .ytp-menuitem-label');
for (var i = 0; i < targetItems.length; i++) {
    var potentialTargetItem = targetItems[i].childNodes[0].childNodes[0];

    var quality = potentialTargetItem.innerHTML.split(' ')[0];

    console.log(quality);
}
```

Thanks

**Comment by veredis** [comment]
Sure, no problem. Here you go: https://postimg.cc/1V1xKwmN

Seems like it's not distinguishing the Premium HD option specifically, I'm assuming the "2" means there are two 1080p options?

**Comment by sameernyaupane** [comment]
Yea, seems to repeat the same name. Hmm
Try this code instead and lets see what happens:

```
var settingsButton = document.getElementsByClassName('ytp-settings-button')[0];
settingsButton.click();
var buttons = document.getElementsByClassName('ytp-menuitem-label');
for (var i = 0; i < buttons.length; i++) {
    if(buttons[i].innerHTML == 'Quality') {
        buttons[i].click();
    }
};
var targetItems = document.querySelectorAll('.ytp-quality-menu .ytp-menuitem-label');
for (var i = 0; i < targetItems.length; i++) {
    var potentialTargetItem = targetItems[i].childNodes[0].childNodes[0];

    var quality = potentialTargetItem.innerText;

    console.log(quality);
}
```

**Comment by maxmakesmods** [comment]
The output of your last code is

> 1080p Premium HD
> Enhanced bitrate
> 1080p HD
> 720p
> 480p
> 360p
> 240p
> 144p
> Auto

There is an additional div element inside the span:

`<span>1080p Premium <sup class="ytp-swatch-color-white">HD</sup><div class="ytp-premium-label">Enhanced bitrate</div></span>`

vs

`<span>1080p <sup class="ytp-swatch-color-white">HD</sup></span>`

I think the easiest way is to check if the `potentialTargetItem` has a div with class "ytp-premium-label" as child. That would also be a solution agnostic of the user's language.

**Comment by maxmakesmods** [comment]
A crude, yet effective, quick fix could be:

```
        var targetItem;

        var targetItems = document.querySelectorAll('.ytp-quality-menu .ytp-menuitem-label');
        targetItems = Array.from(targetItems).filter(item => !item.innerHTML.includes("ytp-premium-label"));
        
        if (preferredQuality === 'best-available') {
            targetItem = targetItems[0];
        } else {
            targetItem = findTargetItem(preferredQuality, targetItems);
        }

        targetItem.click();
```

(untested)

**Comment by veredis** [comment]
I just implemented the above change and can confirm that it works! Thanks @maxvollmer

**Comment by mvahebi** [comment]
Please let me know if this is unrelated but the quality menu pops up at every video.
Will this fix solve that?

I'm refering to this menu:
![premium-bitrate](https://github.com/user-attachments/assets/87960763-44b6-4f76-9f11-57f66c287c64)

**Comment by veredis** [comment]
yes @Moezenka the fix by maxvollmer will solve that. I have the fix implemented in a fork on my profile, or just add the code above yourself. It seems the author is no longer updating this extension

**Comment by sameernyaupane** [comment]
since people are having issue with this, and the PR is ready, I've merged it. Will release new version on chrome store as well.

**Comment by sameernyaupane** [comment]
extension updated, the updates are sent for review to Google. expect the updates to roll soon.
