### ISSUE TITLE
Only works for english YouTube

### ISSUE THREAD

**Issue by JensForstmann** [sameernyaupane/simple-auto-hd#5]
Just noticed that it won't find the correct buttons to click on if the page isn't in english:

- `'Theater mode (t)'`
- `'Quality'`

Do you accept PRs by any chance? Then I could add language support.
Or do you plan to do it yourself?

**Comment by sameernyaupane** [comment]
Thanks for the heads up, :)
Sure, please send a PR. 
I will review and merge it

**Comment by sameernyaupane** [comment]
Merged,working well. Thanks
I will add it to next release.

**Comment by JensForstmann** [comment]
🥳

Do you already know when you will release the next version?

**Comment by sameernyaupane** [comment]
Will release pretty soon. Need to also do some changes  to use MutationObserver instead of just using timeouts. It'll make the extension much more stable when internet speed varies or page takes time to load.

**Comment by sameernyaupane** [comment]
New version released.
